from pathlib import Path
import hashlib,json,importlib,importlib.metadata as md
out=Path('/home/ts/wt/toad-prompt-action-owner-20261002/.artifacts/native-summary562-status362-receiving-20261003')
owner=json.loads((out/'ownership.json').read_text());prefix=Path(owner['prefix']);native=Path(owner['native']);trusted_cli=str(native/'dist/cli.js')
artifact=json.loads((out/'qualified-source-gates/044-artifact-receipt.json').read_text());previous={'native_manifest':artifact['manifest'],'native_tree':artifact['tree']};manifest_hash=previous['native_manifest']
sources=[]
for name,head,dist in [('agent_comms',owner['core'],'agent-comms'),('toad',owner['toad'],'batrachian-toad'),('textual',owner['textual'],'textual'),('textual_diff_view','8fa7d4d0db993ea3b761c2760ca9b6a56a6251e9','textual-diff-view')]:
 inventory=json.loads((out/(name+'-inventory.json')).read_text());location=Path(importlib.import_module(name).__file__).parent
 direct=json.loads(md.distribution(dist).read_text('direct_url.json'));assert direct['vcs_info']['commit_id']==head
 sources.append({'module':name,'head':head,'location':str(location),'files':len(inventory),'python_files':sum(i['path'].endswith('.py') for i in inventory),'byte_equal':True,'direct_url':direct,'inventory_sha256':hashlib.sha256(json.dumps(inventory,sort_keys=True).encode()).hexdigest()})
sdk=md.version('agent-client-protocol');packages=sorted((d.metadata['Name'],d.version) for d in md.distributions());assert sdk=='0.12.1' and len(packages)==69
before=json.loads((out/'protected-before.json').read_text()); changed=[name for name,digest in before.items() if not Path(name).is_file() or hashlib.sha256(Path(name).read_bytes()).hexdigest()!=digest]; assert not changed,changed
receipt={'state':'Merged560/562+Ready362 normal69 installed union source proof; reviewed native044','prefix':str(prefix),'sources':sources,'native_package':str(native),'native_cli':str(trusted_cli),'native_manifest':manifest_hash,'native_tree':previous['native_tree'],'native_full_trust':True,'sdk':sdk,'package_count':len(packages),'packages':packages,'requirements_sha256':hashlib.sha256((out/'requirements.txt').read_bytes()).hexdigest(),'protected_old_prefix_files':len(before),'protected_old_prefix_files_unchanged':True,'public_install_changed':False,'new_native_build':False,'source_overlay':False,'dependency_bypass':False,'journey_owners':['Einstein362 installed SDK notification/local completion App check','Mendel562 configured native044 saved-session summary->distinctinput->terminal','parent ordinary default already-open configured reply after publication'],'journey_assessment':'Original qualified362 SDK/App status settlement8.4396s (no provider) plus562 genuine configured native044147.617s saved-session summary/commit/distinctinput/terminal. No repeatjourneys/speedclaim; parent already-open default configured reply remains separate final362live proof.'}
(out/'source-proof.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps({'sources':[{k:v for k,v in s.items() if k in ('module','head','files','byte_equal')} for s in sources],'native_full_trust':True,'sdk':sdk,'package_count':len(packages),'prefix':str(prefix)},indent=2))
