#!/usr/bin/env bash
set -euo pipefail
: "${TOAD_TEST_SOURCE:?}" "${TOAD_TEST_FRAMEWORK:?}" "${TOAD_TEST_ENVIRONMENT:?}"
: "${TOAD_TEST_SITE_PACKAGES:?}" "${TOAD_PERF_TOOLS_DIR:?}" "${TOAD_ARTIFACT_ROOT:?}"
export PYTHONDONTWRITEBYTECODE=1
export TMPDIR="$TOAD_ARTIFACT_ROOT"
export PYTHONPATH="$TOAD_PERF_TOOLS_DIR:$TOAD_TEST_SOURCE/src:$TOAD_TEST_FRAMEWORK/src:$TOAD_TEST_SITE_PACKAGES${TOAD_VALIDATION_EXTRA_PYTHONPATH:+:$TOAD_VALIDATION_EXTRA_PYTHONPATH}"
export TEXTUAL_DRIVER=sidebar_validation_driver:ValidationDriver
unset AGENT_COMMS_THREAD AGENT_COMMS_MANAGED PI_AGENT_ID PI_PARENT_ID PI_TASK PI_WORKTREE PI_PROMPT
exec "$TOAD_TEST_ENVIRONMENT/bin/python" "$TOAD_TEST_SOURCE/tests/navigation_terminal_fixture.py"
