#!/usr/bin/env bash
set -euo pipefail
: "${TOAD_TEST_SOURCE:?}" "${TOAD_TEST_FRAMEWORK:?}" "${TOAD_TEST_ENVIRONMENT:?}"
: "${TOAD_TEST_SITE_PACKAGES:?}" "${TOAD_PERF_TOOLS_DIR:?}" "${TOAD_ARTIFACT_ROOT:?}"
: "${AGENT_COMMS_ROOT:?Set an explicit authorized wire root}"
: "${TOAD_LIVE_PROJECT:?}" "${TOAD_LIVE_SESSION:?}" "${TOAD_LIVE_ACP_COMMAND:?}"
export PYTHONDONTWRITEBYTECODE=1
export TMPDIR="$TOAD_ARTIFACT_ROOT"
export PYTHONPATH="$TOAD_PERF_TOOLS_DIR:$TOAD_TEST_SOURCE/src:$TOAD_TEST_FRAMEWORK/src:$TOAD_TEST_SITE_PACKAGES${TOAD_VALIDATION_EXTRA_PYTHONPATH:+:$TOAD_VALIDATION_EXTRA_PYTHONPATH}"
export TEXTUAL_DRIVER=sidebar_validation_driver:ValidationDriver
unset AGENT_COMMS_THREAD AGENT_COMMS_MANAGED PI_AGENT_ID PI_PARENT_ID PI_TASK PI_WORKTREE PI_PROMPT
exec "$TOAD_TEST_ENVIRONMENT/bin/python" "$TOAD_PERF_TOOLS_DIR/run_observed_app.py" \
  acp "$TOAD_LIVE_ACP_COMMAND" "$TOAD_LIVE_PROJECT" \
  --title 'Observed Toad performance run' --session "$TOAD_LIVE_SESSION" --renderer persistent
