from typing import Mapping

from rich.color import Color
from rich.style import Style

SGR_STYLES: Mapping[int, Style] = {
    1: Style(bold=True),
    2: Style(dim=True),
    3: Style(italic=True),
    4: Style(underline=True),
    5: Style(blink=True),
    6: Style(blink=True),
    7: Style(reverse=True),
    8: Style(reverse=True),
    9: Style(strike=True),
    21: Style(underline2=True),
    22: Style(dim=False, bold=False),
    23: Style(italic=False),
    24: Style(underline=False),
    25: Style(blink=False),
    26: Style(blink=False),
    27: Style(reverse=False),
    28: Style.null(),  # "not conceal",
    29: Style(strike=False),
    30: Style(color=Color.from_ansi(0)),
    31: Style(color=Color.from_ansi(1)),
    32: Style(color=Color.from_ansi(2)),
    33: Style(color=Color.from_ansi(3)),
    34: Style(color=Color.from_ansi(4)),
    35: Style(color=Color.from_ansi(5)),
    36: Style(color=Color.from_ansi(6)),
    37: Style(color=Color.from_ansi(7)),
    39: Style(color=Color.default()),
    40: Style(bgcolor=Color.from_ansi(0)),
    41: Style(bgcolor=Color.from_ansi(1)),
    42: Style(bgcolor=Color.from_ansi(2)),
    43: Style(bgcolor=Color.from_ansi(3)),
    44: Style(bgcolor=Color.from_ansi(4)),
    45: Style(bgcolor=Color.from_ansi(5)),
    46: Style(bgcolor=Color.from_ansi(6)),
    47: Style(bgcolor=Color.from_ansi(7)),
    49: Style(bgcolor=Color.default()),
    51: Style.null(),  # "frame",
    52: Style.null(),  # "encircle",
    53: Style.null(),  # "overline",
    54: Style.null(),  # "not frame not encircle",
    55: Style.null(),  # "not overline",
    90: Style(color=Color.from_ansi(8)),
    91: Style(color=Color.from_ansi(9)),
    92: Style(color=Color.from_ansi(10)),
    93: Style(color=Color.from_ansi(11)),
    94: Style(color=Color.from_ansi(12)),
    95: Style(color=Color.from_ansi(13)),
    96: Style(color=Color.from_ansi(14)),
    97: Style(color=Color.from_ansi(15)),
    100: Style(bgcolor=Color.from_ansi(8)),
    101: Style(bgcolor=Color.from_ansi(9)),
    102: Style(bgcolor=Color.from_ansi(10)),
    103: Style(bgcolor=Color.from_ansi(11)),
    104: Style(bgcolor=Color.from_ansi(12)),
    105: Style(bgcolor=Color.from_ansi(13)),
    106: Style(bgcolor=Color.from_ansi(14)),
    107: Style(bgcolor=Color.from_ansi(15)),
}
